// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FacebookBigProfile {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("FacebookPicturePicker")]
	public partial class FacebookPicturePicker {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_cancelButton;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("cancelButton")]
		private MonoTouch.UIKit.UIBarButtonItem cancelButton {
			get {
				this.__mt_cancelButton = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("cancelButton")));
				return this.__mt_cancelButton;
			}
			set {
				this.__mt_cancelButton = value;
				this.SetNativeField("cancelButton", value);
			}
		}
	}
}
