// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FacebookBigProfile {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("MainView")]
	public partial class MainView {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIScrollView __mt_scrollView;
		
		private MonoTouch.UIKit.UIImageView __mt_facebookOverlay;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_libraryButton;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_cameraButton;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_facebookButton;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_splitButton;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("scrollView")]
		private MonoTouch.UIKit.UIScrollView scrollView {
			get {
				this.__mt_scrollView = ((MonoTouch.UIKit.UIScrollView)(this.GetNativeField("scrollView")));
				return this.__mt_scrollView;
			}
			set {
				this.__mt_scrollView = value;
				this.SetNativeField("scrollView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("facebookOverlay")]
		private MonoTouch.UIKit.UIImageView facebookOverlay {
			get {
				this.__mt_facebookOverlay = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("facebookOverlay")));
				return this.__mt_facebookOverlay;
			}
			set {
				this.__mt_facebookOverlay = value;
				this.SetNativeField("facebookOverlay", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("libraryButton")]
		private MonoTouch.UIKit.UIBarButtonItem libraryButton {
			get {
				this.__mt_libraryButton = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("libraryButton")));
				return this.__mt_libraryButton;
			}
			set {
				this.__mt_libraryButton = value;
				this.SetNativeField("libraryButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("cameraButton")]
		private MonoTouch.UIKit.UIBarButtonItem cameraButton {
			get {
				this.__mt_cameraButton = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("cameraButton")));
				return this.__mt_cameraButton;
			}
			set {
				this.__mt_cameraButton = value;
				this.SetNativeField("cameraButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("facebookButton")]
		private MonoTouch.UIKit.UIBarButtonItem facebookButton {
			get {
				this.__mt_facebookButton = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("facebookButton")));
				return this.__mt_facebookButton;
			}
			set {
				this.__mt_facebookButton = value;
				this.SetNativeField("facebookButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("splitButton")]
		private MonoTouch.UIKit.UIBarButtonItem splitButton {
			get {
				this.__mt_splitButton = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("splitButton")));
				return this.__mt_splitButton;
			}
			set {
				this.__mt_splitButton = value;
				this.SetNativeField("splitButton", value);
			}
		}
	}
}
