// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FacebookBigProfile {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("MainView")]
	public partial class MainView {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIScrollView __mt_scrollView;
		
		private MonoTouch.UIKit.UIImageView __mt_facebookOverlay;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_facebookButton;
		
		private MonoTouch.UIKit.UIBarButtonItem __mt_photoButton;
		
		private MonoTouch.UIKit.UIToolbar __mt_toolbar;
		
		private MonoTouch.UIKit.UIPickerView __mt_lineSelector;
		
		private MonoTouch.UIKit.UIButton __mt_lineButton;
		
		private MonoTouch.iAd.ADBannerView __mt_adView;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("scrollView")]
		private MonoTouch.UIKit.UIScrollView scrollView {
			get {
				this.__mt_scrollView = ((MonoTouch.UIKit.UIScrollView)(this.GetNativeField("scrollView")));
				return this.__mt_scrollView;
			}
			set {
				this.__mt_scrollView = value;
				this.SetNativeField("scrollView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("facebookOverlay")]
		private MonoTouch.UIKit.UIImageView facebookOverlay {
			get {
				this.__mt_facebookOverlay = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("facebookOverlay")));
				return this.__mt_facebookOverlay;
			}
			set {
				this.__mt_facebookOverlay = value;
				this.SetNativeField("facebookOverlay", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("facebookButton")]
		private MonoTouch.UIKit.UIBarButtonItem facebookButton {
			get {
				this.__mt_facebookButton = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("facebookButton")));
				return this.__mt_facebookButton;
			}
			set {
				this.__mt_facebookButton = value;
				this.SetNativeField("facebookButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("photoButton")]
		private MonoTouch.UIKit.UIBarButtonItem photoButton {
			get {
				this.__mt_photoButton = ((MonoTouch.UIKit.UIBarButtonItem)(this.GetNativeField("photoButton")));
				return this.__mt_photoButton;
			}
			set {
				this.__mt_photoButton = value;
				this.SetNativeField("photoButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("toolbar")]
		private MonoTouch.UIKit.UIToolbar toolbar {
			get {
				this.__mt_toolbar = ((MonoTouch.UIKit.UIToolbar)(this.GetNativeField("toolbar")));
				return this.__mt_toolbar;
			}
			set {
				this.__mt_toolbar = value;
				this.SetNativeField("toolbar", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lineSelector")]
		private MonoTouch.UIKit.UIPickerView lineSelector {
			get {
				this.__mt_lineSelector = ((MonoTouch.UIKit.UIPickerView)(this.GetNativeField("lineSelector")));
				return this.__mt_lineSelector;
			}
			set {
				this.__mt_lineSelector = value;
				this.SetNativeField("lineSelector", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("lineButton")]
		private MonoTouch.UIKit.UIButton lineButton {
			get {
				this.__mt_lineButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("lineButton")));
				return this.__mt_lineButton;
			}
			set {
				this.__mt_lineButton = value;
				this.SetNativeField("lineButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("adView")]
		private MonoTouch.iAd.ADBannerView adView {
			get {
				this.__mt_adView = ((MonoTouch.iAd.ADBannerView)(this.GetNativeField("adView")));
				return this.__mt_adView;
			}
			set {
				this.__mt_adView = value;
				this.SetNativeField("adView", value);
			}
		}
	}
}
