// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FacebookBigProfile {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		private MonoTouch.UIKit.UIWindow __mt_window;
		
		private MonoTouch.UIKit.UIButton __mt_myButton;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Export("buttonPressed:")]
		partial void buttonPressed (MonoTouch.UIKit.UIButton sender);

		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("myButton")]
		private MonoTouch.UIKit.UIButton myButton {
			get {
				this.__mt_myButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("myButton")));
				return this.__mt_myButton;
			}
			set {
				this.__mt_myButton = value;
				this.SetNativeField("myButton", value);
			}
		}
	}
}
