// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FacebookBigProfile {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("PhotosTableViewCell")]
	public partial class PhotosTableViewCell {
		
		private MonoTouch.UIKit.UITableViewCell __mt_cell;
		
		private MonoTouch.UIKit.UIImageView __mt_img1;
		
		private MonoTouch.UIKit.UIImageView __mt_img2;
		
		private MonoTouch.UIKit.UIImageView __mt_img3;
		
		private MonoTouch.UIKit.UIImageView __mt_img4;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("cell")]
		private MonoTouch.UIKit.UITableViewCell cell {
			get {
				this.__mt_cell = ((MonoTouch.UIKit.UITableViewCell)(this.GetNativeField("cell")));
				return this.__mt_cell;
			}
			set {
				this.__mt_cell = value;
				this.SetNativeField("cell", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("img1")]
		private MonoTouch.UIKit.UIImageView img1 {
			get {
				this.__mt_img1 = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("img1")));
				return this.__mt_img1;
			}
			set {
				this.__mt_img1 = value;
				this.SetNativeField("img1", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("img2")]
		private MonoTouch.UIKit.UIImageView img2 {
			get {
				this.__mt_img2 = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("img2")));
				return this.__mt_img2;
			}
			set {
				this.__mt_img2 = value;
				this.SetNativeField("img2", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("img3")]
		private MonoTouch.UIKit.UIImageView img3 {
			get {
				this.__mt_img3 = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("img3")));
				return this.__mt_img3;
			}
			set {
				this.__mt_img3 = value;
				this.SetNativeField("img3", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("img4")]
		private MonoTouch.UIKit.UIImageView img4 {
			get {
				this.__mt_img4 = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("img4")));
				return this.__mt_img4;
			}
			set {
				this.__mt_img4 = value;
				this.SetNativeField("img4", value);
			}
		}
	}
}
