// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace FacebookBigProfile {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("PhotosTableViewCell")]
	public partial class PhotosTableViewCell {
		
		private MonoTouch.UIKit.UITableViewCell __mt_cell;
		
		private MonoTouch.UIKit.UIButton __mt_btn1;
		
		private MonoTouch.UIKit.UIButton __mt_btn2;
		
		private MonoTouch.UIKit.UIButton __mt_btn3;
		
		private MonoTouch.UIKit.UIButton __mt_btn4;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("cell")]
		private MonoTouch.UIKit.UITableViewCell cell {
			get {
				this.__mt_cell = ((MonoTouch.UIKit.UITableViewCell)(this.GetNativeField("cell")));
				return this.__mt_cell;
			}
			set {
				this.__mt_cell = value;
				this.SetNativeField("cell", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btn1")]
		private MonoTouch.UIKit.UIButton btn1 {
			get {
				this.__mt_btn1 = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btn1")));
				return this.__mt_btn1;
			}
			set {
				this.__mt_btn1 = value;
				this.SetNativeField("btn1", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btn2")]
		private MonoTouch.UIKit.UIButton btn2 {
			get {
				this.__mt_btn2 = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btn2")));
				return this.__mt_btn2;
			}
			set {
				this.__mt_btn2 = value;
				this.SetNativeField("btn2", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btn3")]
		private MonoTouch.UIKit.UIButton btn3 {
			get {
				this.__mt_btn3 = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btn3")));
				return this.__mt_btn3;
			}
			set {
				this.__mt_btn3 = value;
				this.SetNativeField("btn3", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("btn4")]
		private MonoTouch.UIKit.UIButton btn4 {
			get {
				this.__mt_btn4 = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("btn4")));
				return this.__mt_btn4;
			}
			set {
				this.__mt_btn4 = value;
				this.SetNativeField("btn4", value);
			}
		}
	}
}
